/**
* @File Name : TbtDataPrecacherController .cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 10, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 10, 2025 |   | Initial Version
**/

public class TbtDataPrecacherController  {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}