/**
* @File Name : WorkOrderDynamicListController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 16, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 16, 2025 |   | Initial Version
**/

public class WorkOrderDynamicListController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}